name: Debug

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR base ref: ${{ github.event.pull_request.base.ref }}"
            echo "PR head ref: ${{ github.event.pull_request.head.ref }}"
            echo "PR head sha: ${{ github.event.pull_request.head.sha }}"
          fi